import { Header, Menu } from '@layouts';

import './globals.css';
import type { Metadata } from 'next';

export const metadata: Metadata = {
    title: 'My Color Palette',
    description: 'Generated by create next app'
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="ko">
            <body>
                <div className="relative w-full bg-[#121212]">
                    <Header />
                    <Menu />
                    <main className="mt-[81px] w-full bg-[#121212] [min-height:calc(100vh-81px)]">{children}</main>
                </div>
            </body>
        </html>
    );
}
